[package]
name = "isograph_lang_types"
version = "0.0.4"
edition = "2021"
license = "MIT"

[dependencies]
common_lang_types = { path = "../common_lang_types" }
graphql_lang_types = { path = "../graphql_lang_types" }
intern = { path = "../../relay-crates/intern" }
u32_newtypes = { path = "../u32_newtypes" }
serde = "1.0.197"
thiserror = "1.0.40"
