[package]
name = "validated_isograph_schema"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
graphql_lang_types = { path = "../graphql_lang_types" }
common_lang_types = { path = "../common_lang_types" }
intern = { path = "../../relay-crates/intern" }
isograph_lang_types = { path = "../isograph_lang_types" }
isograph_config = { path = "../isograph_config" }
isograph_lang_parser = { path = "../isograph_lang_parser" }
isograph_schema = { path = "../isograph_schema" }
pico = { path = "../pico" }
pico_macros = { path = "../pico_macros" }
lazy_static = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
